print("-----------------------------------------")
print("Tugas 1 SISOP kelas-A")
print('-----------------------------------------')
print('Nama: Yayang Dimas Saputra')
print('NPM: 2108010102')
print('-----------------------------------------')
print('notes:')
print('-----------------------------------------')
print('Halo dunia')
print('ini adalah skrip Bash pertamaku di linux')
